language: node_js
node_js: lts/*

addons:
  chrome: stable

cache:
  directories:
    - ~/.rvm/gems
    - node_modules

install:
  - npm install
  - gem install cucumber rspec capybara selenium-webdriver chromedriver-helper:1.2

script:
  - npm run build
  - npm run preprod
  - npm run test
